### ISSUE TITLE
ui.h - #include "../deadbeef/plugins/gtkui/gtkui_api.h"

### ISSUE THREAD

**Issue by sla0101** [VolkMilit/deadbeef-infobar#1]
Hello,

If you're still around working on this, thanks...

I noticed a /path problem in ui.h;

https://github.com/VolkMilit/deadbeef-infobar/blob/master/ui.h

Line 27 -  ```#include "../deadbeef/plugins/gtkui/gtkui_api.h"```

From what I understand the default/correct path should be;

```#include "../deadbeef/gtkui_api.h"```

Without this change it doesn't compile for me...

By the way, the original versoin all you needed was the ```ddb_infobar_gtk2.so``` and/or ```ddb_infobar_gtk3.so```. Is this still the same, or do I need to keep the other files?

infobar.o
lyrics.o
ui.o
utils.o

One last thing, before I posted this, I wasn't paying attention to the dates and commits, I don't see there's anything going on here different from the original?

**Comment by VolkMilit** [comment]
I don't know, I don't touched this plugin for a while now. I just cut the unnecessary functionality for me, and my DeadBeef doesn't segfault anymore.
Btw, #include like this is bad practice. You need to install DeadBeef headers from your distribution repository. I think I just miss that failure.
Also I can try to write CMake rule, well, at least I need to, I'm also using this plugin. If you can do that, I'm also appreciate pr.

**Comment by VolkMilit** [comment]
Hmm, I don't think you need to update this plugin, cuz' it works great. I don't know, maybe it was something wrong with my DeadBeef installation, but I'm just a bit of perfectionist, I don't need to all that biography and stuff.
